definitions = [
    "pleasant and peaceful; perfect",
    "very embarrassed",
    "fair",
    "no mistakes",
    "too small of a difference or situation or action to be seen or noticed",
    "hard to believe",
    "not realistic",
    "no respect or/and not polite",
    "done or acting without sensible judgement or not caring for any harmful effects",
    "impossible to be without it",
    "appears to be the same",
    "impossible to solve",
    "too interested to find out what other people are doing",
    "a strong feeling of hate; disgust",
    "feeling embarrassed and guilty because of something that you have done",
    "very bad; shocking",
    "to stop yourself from doing something that you enjoy",
    "very bad; of very poor quality",
    "to make something easier to be noticed",
    "a person that you know but who is not a close friend",
    "the act of obtaining or buying something || something that you have obtained or bought",
    "very sure; refusing to change your mind",
    "enough for what you need; just good enough; acceptable",
    "the period of the person's life from 13 to 17",
    "having a lot of money",
    "capturing or holding someone's attention; fascinating",
    "(of a sound) pleasingly smooth and musical to hear",
    "showing luminous colours that seem to change when seen from different angles",
    "a moment of sudden and great revelation or realisation",
    "lasting for a very short time (but not like a second or something like that)",
    "shaky; quivering; trembling",
    "Intense happiness; blizz",
    "the quality of being graceful and stylish in appearance or manner",
    "very complicated or detailed",
    "in its original condition; unspoilt; clean and fresh as if new; spotless",
    "cheerful and full of energy",
    "magnificent and splendid appearance; grandeur (impressiveness, especially of appearance or style)",
    "(of a man) confident, stylish, and charming",
    "dull, tedious, and repetitious; lacking in variety and interest",
    "tending to induce sleep",
    "quiet and calm",
    "not able to behave well with others",
    "expecting good things to happen or something to be successful in the future",
    "to stop or end",
    "without success",
    "a reason you give for doing something which is not the real reason for doing it",
    "never stopping (usually used for annoyingness)",
    "to make someone who is angry or upset be calm or quiet",
    "an unpleasant and difficult situation that is hard to get out of",
    "to tell somebody something that is a secret",
    "difficult to please; wanting everything to be perfect",
    "almost certain to happen soon (usually used for something unpleasant)",
    "money that you pay to somebody as you have injured him/her or lost/damaged his/her property || a fact or action that reduces or removes the bad effect of something",
    "a very ungrateful person",
    "furiously angry",
    "to accept and allow behaviour that is considered wrong or offensive",
    "dishonest or misleading",
    "extremely bad, horrifying or appalling",
    "to make something easier",
    "meaningless or not important",
    "a secret you do not want anyone to know of",
    "to make somebody angry; to annoy somebody so much",
    "possible results (usually negative) of an action",
    "to completely destroy something bad",
    "the expression of approval or agreement",
    "of many kinds; numerous and varied",
    "suppose that something is true without having evidence to confirm it",
    "express to (someone) one's disapproval of or disappointment in their actions || the expression of disapproval or disappointment",
    "(of a person or their manner) unwilling or unable to believe something.",
    "difficult to control or handle; wildly boisterous",
    "provoking loud laughter; very funny",
    "(of the heart) beating rapidly, strongly, or irregularly",
    "look thoughtfully for a long time at",
    "disconcert or confuse someone",
    "deprived of strength or power; debilitated",
    "giving rise or likely to give rise to public disagreement.",
    "prolonged public disagreement or heated discussion.",
    "arousing intense distaste or disgust.",
    "shorten a word, phrase, or text.",
    "having an unpleasant smell or taste usually from chemical change or decomposition.",
    "extremely unpleasant.",
    "publicly recommend or support.",
    "the customary code of polite behaviour in society or among members of a particular profession or group.",
    "extremely or ususally small",
    "extremely small; tiny",
    "extremely small",
    "a state of awed admiration or respect",
    "losing strength or purpose and stopping, or almost stopping || moving awkwardly as you might fall",
    "the feeling or understanding that makes you believe or know something that is true without being able to explain why",
    "extremely large || relating or belonging to the science of astronomy",
    "the quality of being too proud of your appearance or abilities",
    "to react to something unpleasant that somebody does to you by doing something unpleasant in return",
    "fear or anxiety about something that may happen",
    "so surprised that you cannot speak",
    "a very small piece of something, usually food",
    "relating to the practice of cooking or eating good food",
    "making you want something that you cannot have or do; tempting",
    "a wide range of something",
    "known to be good",
    "very busy with a lot of things that you have to do quickly",
    "the character and atmosphere of the place",
    "a person who can endure pain or hardship without showing their feelings or complaining",
    "to make something shorter by removing parts of it",
    "rough and most likely to scratch",
    "to go up and talk to a stranger in a way that is rube or frightening",
    "to make yourself, somebody or something get used to something",
    "to get to be familiar with something",
    "to accept something without argument, although you may not agree with it",
    "a substance that your body produces when you are very angry, frightened or excited and that makes your heart pump faster",
    "having full use of your body; hysically healthy and strong",
    "something that you say or do that is insulting to somebody or something",
    "(adjective but not before a noun) being planned or prepared",
    "a person who is not sure if God exists or not",
    "to worry or think about something for a very long time",
    "any illness that is not very serious",
    "having or showing a mixture of feelings or opinions about something or somebody",
    "made or done in a friendly way without argument",
    "to cut off a person's body part for medical reasons",
    "a short intresting story about a real person or story",
    "great mental pain and suffering",
    "an illness, especially affecting yound women. It makes them afraid of being so they do not eat",
    "a feeling of hate and of being against somebody / something",
    "to make somebody angry or to annoy somebody",
    "lacking interest or desire to act",
    "relating to the practise of cooking or eating good food",
    "(of food or drink) pleasant to taste || (of an action of proposal) acceptable or satisfactory",
    "done without will or concious control || done against one's will",
    "twisted or bent out of the normal shape",
    "sudden and unexpected",
    "beating with a strong, regular rhythm; pulsating || causing pain in a series of regular beats",
    "without suffering any injury, damage or harm",
    "not aware of or concerned about whar is happening around",
    "full of danger or risk",
    "(of water) pour downwards rapidly and in large quantities",
    "extremely hungry",
    "speak or shout at length in an angry, impassioned way",
    "not easily upset or excited || calm and peaceful, with little movement or activity",
    "trouble or  annoy (someone) with frequent or persistent requests or interruptions",
    "move or cause to move at high speed; typically in an uncontrolled manner",
    "make a gesture with the hand, arm or head to encourage or instruct someone to approach or follow || summon someone by making a gesture with the hand, arm or head to encourage or instruct someone to approach or follow",
    "notsecurely held or in position; dangerously likely to fall or collapse || depend on chance; uncertain",
    "a state or period of stagnation or depression",
    "(of a place) uninhabited and giving an impression of bleak emptiness",
    "a harsh discordant mixture of sounds",
    "combine or unite to form one organization or structure",
    "a person's face or facial expression || support or approval || admit as acceptable or possible",
    "make (someone) unable to breathe properly; suffocate || restrain (a reaction) ir stop oneself acting on (an emotion)",
    "(espeacially of wind or waves) strike repeatedly and voilently",
    "having or displaying a passionate intensity",
    "feel comtempt or a deep repugnance for",
    "the feeling that a person or a thing is worthless or beneath consideration",
    "intense disgust",
    "express sharp disapproval or critism of (someone) because of their behaviour or actions",
    "remarkable or impressively great in extent, size or degree",
    "involving or requiring strenuous effort; difficult and tiring",
    "a sudden attack or outburst of a particular emotion or activity",
    "a feeling or state of intense excitement or happiness",
    "incapable of producing any useful result; pointless",
    "never ending or changing || occuring repeatedly; so frequently as to seem endless and interrupted",
    "a small space created by building part of a wall further back from the rest",
    "filled with or revealing awe",
    "hurl or launch (something) with or as if with a catapult",
    "make an attack in return of a similar attack || repay (an injury or insult) in kind",
    "attractively small and daintly (used of a woman)",
    "in low spirits from loss of hope and courage",
    "having or displaying a passionate intensity || hot, burning or glowing",
    "exhibiting goodwill and an absence of antagonism",
    "suffer violent involuntary contraction of the muscles, producing contortion of the limbs or body || throw (a country) into violent social or political upheaval",
    "a violent or sudden change or disruption to something",
    "curious or unusual in a way that provokes dry amusement",
    "playfully mischievous || characteristic of a dishonest or unprincipled person",
    "in a manner lacking any obvious principle of organization",
    "without opposition; with the agreement of all people involved",
    "disorderly and disruptive and not amenable to discipline or control",
    "open and responsive to suggestion; easily persuaded or controlled || capable of being acted upon in a particular way; suceptible",
    "deep blue in colour",
    "admit or agree that something is true after first denying or resisting || surrender or yield (a possession, right and privilege)",
    "deriving pleasure from inflicting pain, suffering or humiliation on others",
    "outward behaviour or bearing",
    "extreme tiredness; fatigue",
    "(of rain) falling rapidly in capious quantities",
    "stunted in growth or delevopment",
    "not considered to be respectable in character or appearance",
    "having a specified level of determination",
    "become less servere, intense or violent",
    "the process of burning",
    "a large or excessive amount of something",
    "(used about a man) strong and attractive || (used about land) rough, with lot of rocks and not many plants || strong and made for difficult conditions",
    "wishing to hurt others",
    "extremely unpleasant; disgusting",
    "very careful or paying great attention to detail || careful to do what is right or honest",
    "(used about a person) pleasant and friendly",
    "intended as a punishment || very harsh that people find diffcult to pay",
    "very strange or unusual",
    "not having or showing good judgement about what is attractive or appropriate; not polite or well behaved || rude or likely to offend people",
    "to persuade someone gently",
    "healthy and strong; full of vigour",
    "make something more attractive by the addtion of decorative details or features || make a statement or story more interesting by adding extra details that are often untrue",
    "(of a crowd) fill or be present in a place or area || flock or be present in great numbers",
    "nearly; almost",
    "wild and noisy disorder or confusion; uproar",
    "an act or incident involving excitement, daring or adventure",
    "happen or occur afterwards or as a result",
    "(of a product or piece of artistic work) reproduced without permission usually in contravention of patent or copyright",
    "an action which offends against a law, treaty, or other ruling",
    "a sudden and ignominious failure; a fiasco",
    "the act of shaping into parallel ridges and grooves",
    "(of a living organism) grow or develop in a healthy or vigorous way, especially as the result of a particularly congenial environment // wave (something) about to attract attention (verb)",
    "(of a person) pleasing or liked on account of having qualities or interests that are similar to one's own // (of a thing) pleasant or agreeable because suited to one's tase or inclination (adjective)",
    "a small amount of substance (noun)",
    "pellets of frozen rain which fall in showers from cumulonimbus clouds // hail falls // (of a large number of objects) fall or be hurled forcefully // call out to (someone) to attract attention // signal (an approaching taxi) to stop // praise (someone or something) enthusiastically // have one's home or origins in (a place); come from // a shout or call used to attract attention (noun(1,8) verb(2,3,4,5,6,7))",
    "clouds forming a towering mass with a flat base at fairly low altitude and often a flat top, as in thunderstorms (noun)",
    "behaving or looking as though one thinks one is superior to other (adjective)",
    "approach and address (someone) boldly and aggressively (verb)",
    "occasionally or at irregular intevals (adverb)",
    "to sing or hum in a sweet, low voice full of emotion (verb)",
    "a slow, sentimental song (noun)",
    "in a manner that is so delicate or precise as to be difficult to analyse or describe // in a clever and indirect way, in order to achieve something (adverb)",
    "able to be seen or understood (adjective)",
    "(especially of a slight movement or change of state) able to be seen or noticed (adjective)",
    "unnecessary, especially through being more than enough. (adj)",
    "existing or occuring only on the surface without much depth or consideration of things that are important or serious (adj)",
    "relating to or situated on the edge or periphery of something // of secondary or minor importance; marginal (adj)",
    "the outer limits or edge of an area or object // a marginal or secondary position in, or asect of, a group, subject or sphere of activity (noun)",
    "say something in answer to a remark, typically in a sharp, angry, or witty manner // a sharp, angry or witty reply (verb(1), noun(2))",
    "perfectly clean, neat or tidy (adj)",
    "an illogical or surprising lack of compatibility or similarity between two or more facts (noun)",
    "with great attention to detail; meticulously (adverb)",
    "take in and understand fully (information or ideas) (verb)",
    "make (something) pyshically stronger or more solid // strengthen (one's position or power) // combine (a number of things) into a single more effective or coherent whole (verb)",
    "make (an idea or concept) real; give specific or definite form to (verb)",
    "(of alcoholic drink or a drug) cause (someone) to lose control of the faculities or behaviour // excite or exhiarate (someone) (verb)",
    "make (someone) drunk; intoxicate // a drunkard // drunk; intoxicated (verb(1), noun(2,3))",
    "give (someone) pleasure or satisfaction // indulge or satisfy (a desire) (verb)",
    "give intense pleasure or joy to (verb)",
    "the quality of being powerfully and mysteriously attractive or fasinating // powerfully attract or charm; tempt (noun(1), verb(2))",
    "to be likely to suffer from, do or experience something unpleasant or regrettable // lying flat, espeacially face downards (adjective)",
    "likely on liable to be influenced or harmed by a particular thing // (of a person) easily influenced by feelings or emotions; sensitive // capable or admitting of (adjective)",
    "a long period with little or no rain, resulting in a shortage of water (noun)",
    "become progressively worse (verb)",
    "a sudden occurrence of something unpleasant or dangerous (noun)",
    "the fact that something is common (noun)",
    "an involuntary quivering moment // a slight earthquake // undergo a tremor or tremors (noun(1,2), verb(3))",
    "an established or offical way of doing something // a surgical operation // a series of actions conducted in a certain order or manner (noun)",
    "suceed in persuading or leading (someone) to do something // bring about or give rise to; to cause something to happen",
    "prove more powerful or superior // persuade (someone) to do something (verb)",
    "to make (something) more noticable; prominent (verb)",
]
