phrase_list = [
    "The silence was as deep as the ocean's abyss.",
    "His smile was as bright as the morning sun.",
    "The forest was a symphony of whispers.",
    "Her gaze was as sharp as a hawk's.",
    "The city was an orchestra of lights.",
    "The night was a velvet curtain of dreams.",
    "The waves danced to a silent rhythm.",
    "Her laughter was a river of joy.",
    "The rain was a tap dance on the roof.",
    "His words were the keys to an unopened door.",
    "The flowers swayed in the gentle breeze like ballet dancers on a moonlit stage.",
    "The house stood like a sentinel, guarding its secrets in the silence of the night.",
    "Her eyes were pools of mystery, reflecting the secrets of the universe.",
    "The market was a symphony of scents, each stall a different note in the melody.",
    "The mountain peaks kissed the sky in an eternal embrace.",
    "The desert stretched to infinity, a sea of golden sands.",
    "The library was a labyrinth of knowledge, each book a hidden treasure.",
    "Her voice flowed like a river, carrying the stories of generations.",
    "The storm raged like a furious beast, shaking the world with its anger.",
    "The garden bloomed like a thousand rainbows, each flower a different colour.",
    "Time is a river, sweeping us along in its current.",
    "Her voice was a lighthouse in the sea of chaos, guiding us home.",
    "His heart was a locked door, and she held the key.",
    "The city was a patchwork quilt of cultures, each square telling a different story.",
    "Her laughter was a melody, playing the notes of happiness.",
    "The forest was a cathedral of trees, with branches reaching towards the heavens.",
    "The desert was a sea of sand, with dunes like waves frozen in time.",
    "His mind was a library, with shelves of knowledge waiting to be explored.",
    "Her smile was a ray of sunshine, breaking through the clouds of despair.",
    "The journey of life is a winding road, with twists and turns along the way.",
    "She worked tirelessly, juggling tasks like a circus performer mastering a complex routine.",
    "The old man's wisdom was as deep as the ocean, with hidden treasures beneath the surface.",
    "The children's laughter filled the room like bubbles of joy rising to the surface.",
    "The sunsets in that place were as breathtaking as a painter's masterpiece.",
    "The aroma of freshly baked bread wafted through the air, a symphony for the senses.",
    "His words were as sharp as a sword, cutting through the confusion with precision.",
    "Her kindness was as warm as a cosy blanket on a winter's night.",
    "The garden was a paradise of colours, with flowers like jewels in the sunlight.",
    "The party was a whirlwind of excitement, with laughter and music filling the air.",
    "Their love was as strong as a mighty oak, weathering the storms of life.",
    "His ideas were a constellation of innovation in a sea of conformity.",
    "The raindrops were notes in nature's symphony.",
    "The city was a canvas of stories waiting to be told.",
    "Her mind was a garden, with thoughts as vibrant as blooming flowers.",
    "The waves were dancers, moving in harmony with the rhythm of the ocean.",
    "The forest was a tapestry of life, with each tree a different thread.",
    "His courage was a blazing fire, lighting the path of determination.",
    "Her dreams were constellations in the night sky of possibilities.",
    "The journey of life was an epic adventure, with each day a new chapter.",
    "The city streets were a maze of stories, waiting to be explored.",
    "Her voice was as soothing as a gentle breeze on a summer's day.",
    "The mountains stood tall like ancient sentinels, guarding the secrets of the valley.",
    "The waves crashed on the shore like applause from the sea.",
    "His determination burned as fiercely as a wildfire.",
    "The smile on her face was as bright as a thousand suns.",
    "The room was as silent as a library at midnight.",
    "The book was as heavy as a stone, filled with knowledge.",
    "His laughter was as infectious as a bout of laughter in a comedy club.",
    "Her eyes sparkled like stars in the night sky.",
    "The rain fell like a curtain of silver, shimmering in the moonlight.",
    "The old house creaked and whispered its secrets, its timeworn walls echoing with the voices of the past.",
    "The garden was a paradise of colour, with flowers like jewels in the sunlight.",
    "The city at night was a cascade of neon, like a river of light flowing through the streets.",
    "The forest was a tapestry of emerald, each leaf a brushstroke of life.",
    "The waves crashed on the shore, a thunderous applause from the sea.",
    "The market was a labyrinth of scents, each stall a different note in the melody.",
    "The desert stretched to infinity, a sea of golden sands.",
    "The library was a treasure trove of knowledge, with books as keys to different worlds.",
    "The city skyline was a forest of steel and glass, reaching for the sky.",
    "Her laughter was a river of joy, carrying away all worries in its current.",
    "Her eyes sparkled with the mischief of a child, even in the face of adversity.",
    "His voice carried the weight of a thousand sorrows, resonating with the pain of the world.",
    "The sunset painted the sky with hues of longing, as the day bid a reluctant farewell.",
    "Her words were a balm for a wounded heart, soothing the ache of loneliness.",
    "The music swirled in the air, wrapping the audience in a blanket of nostalgia and joy.",
    "His smile was a beacon of hope, lighting up even the darkest of days.",
    "The story unfolded like a flower in bloom, each chapter revealing a new petal of wonder.",
    "Her tears fell like rain, washing away the dust of sorrow from her soul.",
    "The embrace of a loved one was a sanctuary, a refuge from the storms of life.",
    "The words of the poet were a mirror, reflecting the deepest emotions of the human heart.",
    "His words were a beacon in the storm of confusion, guiding us to clarity.",
    "The painting was a labyrinth of colours, each shade revealing a different facet of the artist's soul.",
    "The river flowed like a silver thread through the heart of the city, connecting past and present.",
    "The city streets were a web of possibilities, where dreams and reality intertwined.",
    "Her smile was a bridge between two worlds, a connection between hearts.",
    "The story was a puzzle, with each word a piece waiting to be placed in the reader's mind.",
    "The sky was a canvas of dreams, where the imagination painted its desires.",
    "His laughter was a symphony of happiness, a celebration of life.",
    "The forest was a cathedral of trees, with each one holding a different story.",
    "The journey of life was a winding road, with twists and turns leading to unknown destinations.",
    "Each sentence flowed into the next like a river winding through a lush, untouched forest.",
    "The story's rhythm was a heartbeat, pulsating with anticipation.",
    "The dialogue danced across the page, a lively conversation between characters.",
    "The narrative was a river, meandering through the landscape of the plot.",
    "The paragraphs were like stepping stones, leading the reader deeper into the story.",
    "The words cascaded down the page like a waterfall, creating a sense of movement.",
    "The chapters were like rooms in a grand mansion, each one revealing a new aspect of the story.",
    "The pacing of the narrative was like a well-conducted orchestra, building tension and excitement.",
    "The sentences were like brushstrokes on a canvas, creating a vivid picture in the reader's mind.",
    "The story unfolded like a journey, with each word a step towards the destination.",
]
